input_variables:
    [JetGood_pt, JetGood_eta, JetGood_phi, JetGood_mass, JetGood_btagPNetB]

preprocess_variables_functions: {}

signal_sample: [VBF_HHto4B]
background_sample: [GluGlutoHHto4B]

signal_region: [4b_region] 
background_region: [4b_region] 

signal_dataset: [VBFHHto4B_CV_1_C2V_1_C3_1_2022_postEE]
background_dataset: [GluGlutoHHto4B_kl-1p00_kt-1p00_c2-0p00__2022_postEE]

ML_model: DNN_model

data_format: coffea
verbosity: info

seed: 1

batch_size: 512
epochs: 50

learning_rate: 1e-2
learning_rate_schedule: linear

early_stopping: False
patience: 5
min_delta: 1e-5

eval_param: "loss"

train_fraction: 0.5
val_fraction: 0.25
test_fraction: 0.25

run2: False

# class balancing
oversample_split: False
split_oversample: False
undersample: False

num_workers: 4
data_dirs: [/work/mmalucch/out_hh4b/out_vbf_ggf_dnn_full/]
eval: True
gpus: '0'
histos: True
roc: True
history: True
eval_model: ''
load_model: ''
onnx: True
pin_memory: False
overwrite: False
output_dir: null
