input_variables: bkg_morphing_dnn_input_variables

signal_sample: [DATA_JetMET_JMENano_E_skimmed]
background_sample: [DATA_JetMET_JMENano_E_skimmed]

run2: False
signal_region: [4b_control_region]
background_region: [2b_control_region_preW]
signal_dataset: [DATA_JetMET_JMENano_E_2022_postEE_EraE]
background_dataset: [DATA_JetMET_JMENano_E_2022_postEE_EraE]
oversample_split: True

ML_model: DNN_softmax_reweight_model

data_format: coffea

batch_size: 64
epochs: 5

learning_rate: 1e-3
learning_rate_schedule: e20_drop75

early_stopping: True
patience: 5
min_delta: 1e-5

eval_param: "acc"

train_fraction: 0.2
val_fraction: 0.1
test_fraction: 0.1

data_dirs: [/work/mmalucch/out_hh4b/out_DATA_spanet_ptflat_btag5WP_ArctanhDeltaProb/]
