input_variables: sig_bkg_dnn_input_variables

run2: False

signal_region: [4b_signal_region]
background_region: [2b_signal_region_postW]
signal_sample: [GluGlutoHHto4B_spanet_skimmed]
background_sample:
  [
    DATA_JetMET_JMENano_E_skimmed,
    DATA_JetMET_JMENano_F_skimmed,
    DATA_JetMET_JMENano_G_skimmed,
  ]
signal_dataset:
  [
    GluGlutoHHto4B_spanet_kl-1p00_kt-1p00_c2-0p00_2022_postEE,
    GluGlutoHHto4B_spanet_kl-0p00_kt-0p00_c2-0p00_2022_postEE,
    GluGlutoHHto4B_spanet_kl-0p50_kt-1p00_c2-0p00_2022_postEE,
    GluGlutoHHto4B_spanet_kl-1p50_kt-1p00_c2-0p00_2022_postEE,
    GluGlutoHHto4B_spanet_kl-2p00_kt-1p00_c2-0p00_2022_postEE,
    GluGlutoHHto4B_spanet_kl-2p45_kt-1p00_c2-0p00_2022_postEE,
    GluGlutoHHto4B_spanet_kl-3p00_kt-1p00_c2-0p00_2022_postEE,
    GluGlutoHHto4B_spanet_kl-3p50_kt-1p00_c2-0p00_2022_postEE,
    GluGlutoHHto4B_spanet_kl-4p00_kt-1p00_c2-0p00_2022_postEE,
    GluGlutoHHto4B_spanet_kl-5p00_kt-1p00_c2-0p00_2022_postEE,
    GluGlutoHHto4B_spanet_kl-m1p00_kt-1p00_c2-0p00_2022_postEE,
    GluGlutoHHto4B_spanet_kl-m2p00_kt-1p00_c2-0p00_2022_postEE,
  ]
background_dataset:
  [
    DATA_JetMET_JMENano_E_2022_postEE_EraE,
    DATA_JetMET_JMENano_F_2022_postEE_EraF,
    DATA_JetMET_JMENano_G_2022_postEE_EraG,
  ]

# split_oversample: True

ML_model: DNN_softmax_reweight_model

data_format: coffea

batch_size: 512
epochs: 50

learning_rate: 1e-3
learning_rate_schedule: e5_drop75

early_stopping: True
patience: 5
min_delta: 1e-5

eval_param: "loss"

train_fraction: 0.7125
val_fraction: 0.2375
test_fraction: 0.05

data_dirs:
  [
    /work/bevila_t/PostDoc/HH4b/Output/PocketCoffea/SPANet_3WPs_bkg_reweight_NoDeltaProb_251011/
  ]
