input_variables: sig_bkg_dnn_input_variables

run2: True

signal_dataset: [GluGlutoHHto4B_kl-1p00_kt-1p00_c2-0p00_spanet__2022_postEE]
signal_sample: [GluGlutoHHto4B_spanet]
signal_region: [4b_signal_regionRun2]

background_dataset: [DATA_JetMET_JMENano_C_2022_preEE_EraC,DATA_JetMET_JMENano_D_2022_preEE_EraD,DATA_JetMET_JMENano_2022_postEE_EraE,DATA_JetMET_JMENano_F_2022_postEE_EraF,DATA_JetMET_JMENano_G_2022_postEE_EraG]
background_sample: [DATA_JetMET_JMENano_C_skimmed,DATA_JetMET_JMENano_D_skimmed,DATA_JetMET_JMENano_E_skimmed,DATA_JetMET_JMENano_F_skimmed,DATA_JetMET_JMENano_G_skimmed]
background_region: [2b_signal_region_postWRun2]

split_oversample: True

ML_model: DNN_softmax_reweight_model

data_format: coffea

batch_size: 512
epochs: 50

learning_rate: 1e-3
#learning_rate_schedule: constant
learning_rate_schedule: e20_drop75

early_stopping: True
patience: 5
min_delta: 1e-5

eval_param: "acc"

train_fraction: 0.7125
val_fraction: 0.2375
test_fraction: 0.05

data_dirs: [/work/tharte/datasets/data_samples/bg_morph_2022_DHH_method/merged_DATA_MC/]
