input_variables: null

signal_sample: [DATA_JetMET_JMENano_C_skimmed]
background_sample: [DATA_JetMET_JMENano_C_skimmed]

signal_region: [4b_control_regionRun2]
background_region: [2b_control_region_preWRun2]
signal_dataset: [DATA_JetMET_JMENano_C_2022_preEE_EraC,DATA_JetMET_JMENano_D_2022_preEE_EraD,DATA_JetMET_JMENano_2022_postEE_EraE,DATA_JetMET_JMENano_F_2022_postEE_EraF,DATA_JetMET_JMENano_G_2022_postEE_EraG]
background_dataset: [DATA_JetMET_JMENano_C_2022_preEE_EraC,DATA_JetMET_JMENano_D_2022_preEE_EraD,DATA_JetMET_JMENano_2022_postEE_EraE,DATA_JetMET_JMENano_F_2022_postEE_EraF,DATA_JetMET_JMENano_G_2022_postEE_EraG]
oversample: True

ML_model: DNN_AN_reweight_model

data_format: coffea

batch_size: 10
epochs: 1

learning_rate: 5e-3
#learning_rate_schedule: constant
learning_rate_schedule: delayed_drop

early_stopping: True
patience: 10
min_delta: 0

eval_param: "acc"

train_fraction: 0.1
val_fraction: 0.05
test_fraction: 0.05

data_dirs: [/work/tharte/datasets/data_samples/data_full_2022/merged/]

overwrite: True

eval: False
onnx: False
histos: False
roc: False
history: False