input_variables:
    [JetGood_pt, JetGood_eta, JetGood_phi, JetGood_mass, JetGood_btagPNetB]

signal_list: [VBF_HHto4B]
background_list: [GluGlutoHHto4B]

ML_model: models.DNN_model

data_format: coffea
