input_variables: null
# input_variables: [JetGoodFromHiggsOrderedRun2_N]

signal_list: [DATA_JetMET_JMENano_skimmed]
background_list: [DATA_JetMET_JMENano_skimmed]

# region: 4b_region 
signal_region: 4b_control_regionRun2
background_region: 2b_control_region_preWRun2
dataset_signal: DATA_JetMET_JMENano_2022_postEE_EraE
dataset_background: DATA_JetMET_JMENano_2022_postEE_EraE

ML_model: models.DNN_reweight_model

data_format: coffea

batch_size: 512
epochs: 50

learning_rate: 1e-2
learning_rate_schedule: delayed_drop

early_stopping: True
patience: 5
min_delta: 0

eval_param: "acc"

train_fraction: 0.5
val_fraction: 0.25
test_fraction: 0.25
