input_variables:
    [JetGood_pt, JetGood_eta, JetGood_phi, JetGood_mass, JetGood_btagPNetB]

signal_sample: [VBF_HHto4B]
background_sample: [GluGlutoHHto4B]

signal_region: [4b_region] 
background_region: [4b_region] 

signal_dataset: [VBFHHto4B_CV_1_C2V_1_C3_1_2022_postEE]
background_dataset: [GluGlutoHHto4B_kl-1p00_kt-1p00_c2-0p00__2022_postEE]

ML_model: models.DNN_model

data_format: coffea

batch_size: 512
epochs: 2

learning_rate: 1e-3
learning_rate_schedule: linear

train_fraction: 0.1
val_fraction: 0.05
test_fraction: 0.05

overwrite: True
