input_variables:
    [JetVBFLeadingMjjNotFromHiggs_pt, JetVBFLeadingMjjNotFromHiggs_eta, JetVBFLeadingMjjNotFromHiggs_phi, JetVBFLeadingMjjNotFromHiggs_mass,
    JetGoodFromHiggsOrdered_pt, JetGoodFromHiggsOrdered_eta, JetGoodFromHiggsOrdered_phi, JetGoodFromHiggsOrdered_mass,
    HiggsLeading_pt, HiggsLeading_eta, HiggsLeading_phi, HiggsLeading_mass,
    HiggsSubLeading_pt, HiggsSubLeading_eta, HiggsSubLeading_phi, HiggsSubLeading_mass,
    events_HH_deltaR, events_H1j1_deltaR, events_H1j2_deltaR, events_H2j1_deltaR, events_H2j2_deltaR, events_HH_centrality,
    events_JetVBFLeadingMjjNotFromHiggs_deltaEta, events_JetVBFLeadingMjjNotFromHiggs_jjMass,
    HH_pt, HH_eta, HH_phi, HH_mass]

signal_sample: [VBF_HHto4B]
background_sample: [GluGlutoHHto4B]

signal_region: [4b_semiTight_LeadingMjj_region] 
background_region: [4b_semiTight_LeadingMjj_region] 

signal_dataset: [VBFHHto4B_CV_1_C2V_1_C3_1_2022_postEE]
background_dataset: [GluGlutoHHto4B_kl-1p00_kt-1p00_c2-0p00__2022_postEE]

ML_model: DNN_model

data_format: coffea

batch_size: 512
epochs: 100

learning_rate: 1e-3
learning_rate_schedule: constant

train_fraction: 0.8
val_fraction: 0.1
test_fraction: 0.1