input_variables: bkg_morphing_dnn_input_variables
# input_variables: [JetGoodFromHiggsOrderedRun2_N]

signal_sample: [DATA_JetMET_JMENano_E_skimmed,DATA_JetMET_JMENano_F_skimmed,DATA_JetMET_JMENano_G_skimmed]
background_sample: [DATA_JetMET_JMENano_E_skimmed,DATA_JetMET_JMENano_F_skimmed,DATA_JetMET_JMENano_G_skimmed]

# region: 4b_region
run2: True
signal_region: [4b_control_regionRun2]
background_region: [2b_control_region_preWRun2]
signal_dataset: [DATA_JetMET_JMENano_2022_postEE_EraE,DATA_JetMET_JMENano_F_2022_postEE_EraF,DATA_JetMET_JMENano_G_2022_postEE_EraG]
background_dataset: [DATA_JetMET_JMENano_2022_postEE_EraE,DATA_JetMET_JMENano_F_2022_postEE_EraF,DATA_JetMET_JMENano_G_2022_postEE_EraG]
oversample_split: True

ML_model: DNN_softmax_reweight_model

data_format: coffea

batch_size: 512
epochs: 50

learning_rate: 1e-3
#learning_rate_schedule: constant
learning_rate_schedule: e20_drop75

early_stopping: True
patience: 5
min_delta: 1e-5

eval_param: "acc"

train_fraction: 0.7125
val_fraction: 0.2375
test_fraction: 0.05

data_dirs: [/work/tharte/datasets/data_samples/data_full_2022/merged/]
